# -*- coding: utf-8 -*-
"""scrapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OseKa2Wf_QBQz2usKwZTg-lDoujuaqM4
"""

!pip install google-play-scraper

from google_play_scraper import app
import pandas as pd
import numpy as np

from google_play_scraper import Sort, reviews

result, continuation = reviews(
     'com.gojek.app',
     lang='id',
     country='id',
     sort=Sort.NEWEST,
     count=30000,
     filter_score_with=None
 )

data = pd.DataFrame(np.array(result), columns=['review'])
data = data.join(pd.DataFrame(data.pop('review').tolist()))
data.head()

data.shape

# # Menambahkan kolom "Kota"
num_rows = data.shape[0]

# # Daftar kota di Jakarta
sumut = ['Medan', 'Kisaran', 'Pematang Siantar', 'Tebing Tinggi', 'Binjai']

# # Menambahkan kolom "Kota" dengan nilai acak
data['kota'] = np.random.choice(sumut, size=num_rows)

# # Tampilkan beberapa data
data.head()

# Simpan data
data.to_csv('reviews_gojek.csv', index=False)